import { create } from "zustand";
import { persist } from "zustand/middleware";

export interface Job {
  id: string;
  title: string;
  companyName: string;
  industry: string;
  category: string;
  logo: string;
  location: string;
  salaryRange: string;
  jobType: string;
  experienceRequired: string;
  description: string;
  requirements: string[];
  benefits: string[];
  postedAt: string;
  applicantsCount: number;
  isFeatured: boolean;
  isNew: boolean;
  matchScore?: number;
}

export interface JobApplication {
  id: string;
  jobId: string;
  jobTitle: string;
  companyName: string;
  candidateId: string;
  candidateName: string;
  candidateTitle: string;
  status: "Under Review" | "Shortlisted" | "Interview Scheduled" | "Offer Received" | "Rejected";
  appliedDate: string;
  cvUrl: string;
  coverLetter?: string;
  matchScore: number;
}

export interface FilterSettings {
  keyword: string;
  location: string;
  minSalary: string;
  maxSalary: string;
  experience: string;
  jobType: string;
  isRemote: boolean;
}

interface JobState {
  jobs: Job[];
  applications: JobApplication[];
  savedJobIds: string[];
  filters: FilterSettings;
  setFilters: (filters: Partial<FilterSettings>) => void;
  resetFilters: () => void;
  postJob: (job: Omit<Job, "id" | "postedAt" | "applicantsCount" | "isNew">) => void;
  editJob: (id: string, updatedJob: Partial<Job>) => void;
  deleteJob: (id: string) => void;
  applyJob: (jobId: string, candidateId: string, candidateName: string, candidateTitle: string, coverLetter?: string, matchScore?: number) => void;
  updateApplicationStatus: (applicationId: string, status: JobApplication["status"]) => void;
  toggleSaveJob: (jobId: string) => void;
  calculateMatchScore: (candidateSkills: { name: string; rating: number }[], jobRequirements: string[]) => number;
}

const defaultJobs: Job[] = [
  // === FULL TIME JOBS (15 Jobs) ===
  {
    id: "job-1",
    title: "Senior Frontend Developer",
    companyName: "Systems Limited",
    industry: "Technology, IT Services",
    category: "IT & Software",
    logo: "SL",
    location: "Lahore, Punjab",
    salaryRange: "PKR 180k - 250k",
    jobType: "Full Time",
    experienceRequired: "3-5 Yrs",
    description: "We are seeking a Senior Frontend Developer to lead the design and implementation of modern web applications. You will collaborate with product management and UX design to create robust user experiences.",
    requirements: ["React.js", "TypeScript", "JavaScript", "Tailwind CSS", "Redux Toolkit", "Git & GitHub"],
    benefits: ["Medical Insurance", "Provident Fund", "Performance Bonus", "Annual Leaves"],
    postedAt: "1 day ago",
    applicantsCount: 24,
    isFeatured: true,
    isNew: true,
    matchScore: 95,
  },
  {
    id: "job-2",
    title: "AI/ML Engineer",
    companyName: "NetSol Technologies",
    industry: "Software Development",
    category: "AI & Data",
    logo: "NS",
    location: "Islamabad",
    salaryRange: "PKR 200k - 300k",
    jobType: "Full Time",
    experienceRequired: "2-4 Yrs",
    description: "NetSol is looking for a talented AI/ML Engineer to design and deploy scalable machine learning architectures. You will construct model pipelines for predictive analysis and automated recommendations.",
    requirements: ["Python", "PyTorch", "TensorFlow", "Machine Learning", "TypeScript", "SQL"],
    benefits: ["Flexible Hours", "Health Care", "Equity Options", "Gym Membership"],
    postedAt: "2 days ago",
    applicantsCount: 15,
    isFeatured: true,
    isNew: true,
    matchScore: 93,
  },
  {
    id: "job-3",
    title: "Product Designer",
    companyName: "10Pearls",
    industry: "IT Services & Consulting",
    category: "Graphic Design",
    logo: "10P",
    location: "Karachi, Sindh",
    salaryRange: "PKR 120k - 180k",
    jobType: "Full Time",
    experienceRequired: "2-4 Yrs",
    description: "10Pearls is seeking a Product Designer who has a strong grasp of user-centered design principles. You will create user flows, mockups, wireframes, and clickable prototypes.",
    requirements: ["Figma", "Adobe XD", "UI Design", "UX Research", "Wireframing", "React.js"],
    benefits: ["Life Insurance", "Paid Training", "Annual Trips", "Internet Allowance"],
    postedAt: "3 days ago",
    applicantsCount: 42,
    isFeatured: true,
    isNew: false,
    matchScore: 91,
  },
  {
    id: "job-4",
    title: "Digital Marketing Specialist",
    companyName: "Daraz",
    industry: "E-commerce",
    category: "Marketing",
    logo: "DZ",
    location: "Remote",
    salaryRange: "PKR 80k - 120k",
    jobType: "Full Time",
    experienceRequired: "1-3 Yrs",
    description: "Join Pakistan's largest e-commerce network. As a Digital Marketing Specialist, you will manage SEM/SEO campaigns, analyze marketing funnels, and optimize conversion metrics.",
    requirements: ["Google Ads", "SEO Optimization", "Google Analytics", "Content Strategy", "Social Media Marketing"],
    benefits: ["Remote Work Allowance", "Employee Discount", "Performance Bonuses", "Learning Allowance"],
    postedAt: "4 days ago",
    applicantsCount: 18,
    isFeatured: true,
    isNew: true,
    matchScore: 90,
  },
  {
    id: "job-5",
    title: "UX Researcher",
    companyName: "Systems Limited",
    industry: "Technology, IT Services",
    category: "Graphic Design",
    logo: "SL",
    location: "Lahore, Punjab",
    salaryRange: "PKR 150k - 200k",
    jobType: "Full Time",
    experienceRequired: "2-4 Yrs",
    description: "Conduct user interviews, design surveys, and compile usability test reports to inform product architectures for high-traffic enterprise solutions.",
    requirements: ["UX Research", "Usability Testing", "User Personas", "Figma", "Information Architecture"],
    benefits: ["Medical coverage", "Gratuity", "Yearly bonuses", "Fuel allowance"],
    postedAt: "5 days ago",
    applicantsCount: 9,
    isFeatured: false,
    isNew: false,
    matchScore: 80,
  },
  {
    id: "job-6",
    title: "Backend Developer",
    companyName: "Habib Bank Limited",
    industry: "Banking & Finance",
    category: "IT & Software",
    logo: "HB",
    location: "Karachi, Sindh",
    salaryRange: "PKR 150k - 200k",
    jobType: "Full Time",
    experienceRequired: "3-5 Yrs",
    description: "HBL is seeking a Backend Developer with specialized skills in building high-availability banking API services, PostgreSQL integrations, and microservices.",
    requirements: ["Node.js", "Express", "PostgreSQL", "REST APIs", "Docker", "JavaScript", "TypeScript"],
    benefits: ["Interest-free loans", "Annual Bonus", "Excellent Healthcare", "Pension Plan"],
    postedAt: "6 days ago",
    applicantsCount: 31,
    isFeatured: false,
    isNew: true,
    matchScore: 85,
  },
  {
    id: "job-7",
    title: "Data Scientist",
    companyName: "Afiniti",
    industry: "AI & Software",
    category: "AI & Data",
    logo: "AF",
    location: "Karachi, Sindh",
    salaryRange: "PKR 250k - 350k",
    jobType: "Full Time",
    experienceRequired: "3-5 Yrs",
    description: "Design and implement statistical analysis models, evaluate predictive algorithms, and collaborate with backend developers to embed ML metrics into banking modules.",
    requirements: ["Python", "Pandas", "Scikit-Learn", "SQL", "Statistics", "Machine Learning"],
    benefits: ["Equity Shares", "Full Health Care", "Conference Budgets", "Gym Allowance"],
    postedAt: "1 week ago",
    applicantsCount: 14,
    isFeatured: true,
    isNew: false,
    matchScore: 92,
  },
  {
    id: "job-8",
    title: "DevOps Engineer",
    companyName: "NetSol Technologies",
    industry: "Software Development",
    category: "IT & Software",
    logo: "NS",
    location: "Remote",
    salaryRange: "PKR 180k - 250k",
    jobType: "Full Time",
    experienceRequired: "3-5 Yrs",
    description: "Manage cloud infrastructure, set up CI/CD pipelines, and maintain high system uptime across AWS services. Experience with Kubernetes is highly valued.",
    requirements: ["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform", "Linux"],
    benefits: ["100% Remote Work", "Device Allowance", "Health Insurance", "Stock options"],
    postedAt: "1 week ago",
    applicantsCount: 11,
    isFeatured: false,
    isNew: true,
    matchScore: 84,
  },
  {
    id: "job-9",
    title: "Business Analyst",
    companyName: "10Pearls",
    industry: "IT Services & Consulting",
    category: "IT & Software",
    logo: "10P",
    location: "Karachi, Sindh",
    salaryRange: "PKR 110k - 160k",
    jobType: "Full Time",
    experienceRequired: "2-4 Yrs",
    description: "Gather client requirements, model enterprise workflows, write product specifications, and act as a liaison between tech developers and business units.",
    requirements: ["Requirements Gathering", "Agile Methodologies", "Jira", "SQL", "Product Roadmap"],
    benefits: ["Gratuity", "Performance bonus", "Training allocations", "Health cover"],
    postedAt: "1 week ago",
    applicantsCount: 29,
    isFeatured: false,
    isNew: true,
    matchScore: 82,
  },
  {
    id: "job-10",
    title: "Financial Controller",
    companyName: "Habib Bank Limited",
    industry: "Banking & Finance",
    category: "Finance",
    logo: "HB",
    location: "Lahore, Punjab",
    salaryRange: "PKR 180k - 260k",
    jobType: "Full Time",
    experienceRequired: "5+ Yrs",
    description: "Oversee company accounts ledger, manage corporate budget constraints, compile cash flow analysis reports, and ensure compliant financial auditing protocols.",
    requirements: ["Accounting", "Corporate Finance", "Auditing", "Excel", "Tax Compliance"],
    benefits: ["Car Allowance", "Medical Insurance", "Yearly Bonus", "Provident Fund"],
    postedAt: "2 days ago",
    applicantsCount: 7,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-11",
    title: "Corporate Tax Consultant",
    companyName: "KPMG Pakistan",
    industry: "Financial Consulting",
    category: "Finance",
    logo: "KP",
    location: "Karachi, Sindh",
    salaryRange: "PKR 130k - 190k",
    jobType: "Full Time",
    experienceRequired: "2-4 Yrs",
    description: "Formulate strategic tax mitigation plans, audit balance sheets for FBR declarations, and represent corporate clients in compliance disputes.",
    requirements: ["Tax law", "Financial Audit", "FBR Compliance", "Communication", "SAP"],
    benefits: ["Health Care", "Transport Pool", "Training Budgets", "Paid Certifications"],
    postedAt: "5 days ago",
    applicantsCount: 12,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-12",
    title: "HR Operations Executive",
    companyName: "Systems Limited",
    industry: "IT Services",
    category: "HR & Recruitment",
    logo: "SL",
    location: "Karachi, Sindh",
    salaryRange: "PKR 80k - 120k",
    jobType: "Full Time",
    experienceRequired: "1-3 Yrs",
    description: "Organize employee onboarding sessions, manage leave logs in internal HRIS, and assist administrative teams in resolving internal query tickets.",
    requirements: ["HRIS Systems", "Employee Relations", "Onboarding", "Communication", "Excel"],
    benefits: ["PF Scheme", "Medical Plan", "Gratuity", "Annual Leaves"],
    postedAt: "3 days ago",
    applicantsCount: 16,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-13",
    title: "Technical Recruiter",
    companyName: "Contour Software",
    industry: "Software Development",
    category: "HR & Recruitment",
    logo: "CS",
    location: "Lahore, Punjab",
    salaryRange: "PKR 90k - 140k",
    jobType: "Full Time",
    experienceRequired: "2-4 Yrs",
    description: "Lead candidate sourcing initiatives on LinkedIn, conduct initial technical screening calls, and schedule interviews for development teams.",
    requirements: ["Talent Sourcing", "Technical Screening", "Communication", "LinkedIn Recruiter", "ATS Systems"],
    benefits: ["Uncapped Commissions", "Health Care", "Paid Internships Allocations", "Fuel Allowance"],
    postedAt: "6 days ago",
    applicantsCount: 22,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "job-14",
    title: "Electrical Power Engineer",
    companyName: "K-Electric",
    industry: "Utilities & Power",
    category: "Engineering",
    logo: "KE",
    location: "Karachi, Sindh",
    salaryRange: "PKR 100k - 150k",
    jobType: "Full Time",
    experienceRequired: "2-4 Yrs",
    description: "Manage grid distribution parameters, identify power load anomalies, and coordinate maintenance sprints across sub-station grids.",
    requirements: ["Power Grid Design", "Electrical Engineering", "MATLAB", "AutoCAD", "Safety Codes"],
    benefits: ["Subsidized Fuel", "Family Medical Cover", "Security Gear Allocation", "Annual Trips"],
    postedAt: "4 days ago",
    applicantsCount: 19,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-15",
    title: "Civil Project Engineer",
    companyName: "Habib Construction Services",
    industry: "Construction & Infrastructure",
    category: "Engineering",
    logo: "HC",
    location: "Lahore, Punjab",
    salaryRange: "PKR 140k - 210k",
    jobType: "Full Time",
    experienceRequired: "3-5 Yrs",
    description: "Supervise daily construction progress, inspect concrete strength logs, manage subcontractor allocations, and ensure safety audit compliance.",
    requirements: ["Project Management", "Structural Design", "AutoCAD", "Civil Engineering", "Excel"],
    benefits: ["Site Allowance", "Project Completion Bonus", "Life Insurance", "Company Car"],
    postedAt: "1 week ago",
    applicantsCount: 34,
    isFeatured: true,
    isNew: false,
  },

  // === PART TIME JOBS (10 Jobs) ===
  {
    id: "job-16",
    title: "Junior React Native Developer",
    companyName: "Arbisoft",
    industry: "IT & Software",
    category: "IT & Software",
    logo: "AS",
    location: "Remote",
    salaryRange: "PKR 60k - 90k",
    jobType: "Part Time",
    experienceRequired: "1-3 Yrs",
    description: "Develop hybrid mobile interfaces using React Native and push features to global App Store directories.",
    requirements: ["React Native", "TypeScript", "JavaScript", "iOS", "Android"],
    benefits: ["Flexible shifts", "Remote stipend", "Internet allowances"],
    postedAt: "2 days ago",
    applicantsCount: 5,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-17",
    title: "Content Copywriter",
    companyName: "Devsinc",
    industry: "IT Services",
    category: "Marketing",
    logo: "DS",
    location: "Faisalabad, Punjab",
    salaryRange: "PKR 45k - 70k",
    jobType: "Part Time",
    experienceRequired: "1-3 Yrs",
    description: "Write content articles for client business landing pages, edit tech newsletters, and optimize blog keywords.",
    requirements: ["SEO Writing", "Technical Content", "Proofreading", "Wordpress"],
    benefits: ["Free meals", "Flexible hours", "Performance commissions"],
    postedAt: "3 days ago",
    applicantsCount: 12,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-18",
    title: "Graphic Design Assistant",
    companyName: "VentureDive",
    industry: "Product Design",
    category: "Graphic Design",
    logo: "VD",
    location: "Lahore, Punjab",
    salaryRange: "PKR 50k - 80k",
    jobType: "Part Time",
    experienceRequired: "Fresh / Intern",
    description: "Assist design leads in preparing client branding assets, banner graphics, and design layouts.",
    requirements: ["Photoshop", "Illustrator", "Branding design", "Typography"],
    benefits: ["Training grants", "Office gym pass", "Fuel cards"],
    postedAt: "4 days ago",
    applicantsCount: 22,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-19",
    title: "SEO Analyst",
    companyName: "Techlogix",
    industry: "IT Sprints",
    category: "Marketing",
    logo: "TL",
    location: "Islamabad",
    salaryRange: "PKR 55k - 85k",
    jobType: "Part Time",
    experienceRequired: "1-3 Yrs",
    description: "Audit Google search crawl loops, implement tags strategies, and trace user search queries maps.",
    requirements: ["Google Analytics", "Ahrefs", "Crawl auditing", "HTML basics"],
    benefits: ["Health care options", "Bonus plans", "Leaves pool"],
    postedAt: "5 days ago",
    applicantsCount: 7,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-20",
    title: "Social Media Coordinator",
    companyName: "TRG Pakistan",
    industry: "Business Services",
    category: "Marketing",
    logo: "TR",
    location: "Karachi, Sindh",
    salaryRange: "PKR 40k - 60k",
    jobType: "Part Time",
    experienceRequired: "Fresh / Intern",
    description: "Monitor user comments lists on corporate social platforms and coordinate posting schedules.",
    requirements: ["Social marketing", "Graphic basics", "Copywriting", "Calendars"],
    benefits: ["Provident fund", "Weekly dinners", "Paid certificates"],
    postedAt: "6 days ago",
    applicantsCount: 14,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-21",
    title: "Python Mentor",
    companyName: "Educative",
    industry: "Online Education",
    category: "Education",
    logo: "ED",
    location: "Lahore, Punjab",
    salaryRange: "PKR 70k - 110k",
    jobType: "Part Time",
    experienceRequired: "2-4 Yrs",
    description: "Help students debug python programming sprints, explain OOP paradigms, and evaluate test files.",
    requirements: ["Python", "Algorithms", "OOP design", "Technical Support"],
    benefits: ["Remote work flexibility", "Mentoring bonuses", "Free courses access"],
    postedAt: "1 week ago",
    applicantsCount: 19,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "job-22",
    title: "Tax Assistant",
    companyName: "PwC Pakistan",
    industry: "Accounting & Auditing",
    category: "Finance",
    logo: "PW",
    location: "Karachi, Sindh",
    salaryRange: "PKR 60k - 95k",
    jobType: "Part Time",
    experienceRequired: "1-3 Yrs",
    description: "Compile transactional ledger files for audit prep, organize invoices, and verify FBR registration details.",
    requirements: ["Accounting basic", "Excel sheets", "FBR auditing", "Bookkeeping"],
    benefits: ["Transport allowances", "Dinner allowances", "Annual bonuses"],
    postedAt: "2 days ago",
    applicantsCount: 11,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-23",
    title: "Technical Support Representative",
    companyName: "Zong 4G (CMPak)",
    industry: "Telecom",
    category: "Customer Support",
    logo: "ZO",
    location: "Rawalpindi, Punjab",
    salaryRange: "PKR 35k - 50k",
    jobType: "Part Time",
    experienceRequired: "Fresh / Intern",
    description: "Resolve client complaints regarding corporate data subscriptions, and verify network connectivity.",
    requirements: ["Troubleshooting", "Active listening", "Network routing", "Call logs"],
    benefits: ["Medical coverage", "Shift allowances", "Dinner facilities"],
    postedAt: "4 days ago",
    applicantsCount: 29,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-24",
    title: "QA Manual Tester",
    companyName: "Arbisoft",
    industry: "IT Services",
    category: "IT & Software",
    logo: "AS",
    location: "Lahore, Punjab",
    salaryRange: "PKR 65k - 100k",
    jobType: "Part Time",
    experienceRequired: "1-3 Yrs",
    description: "Run click test scripts for browser page builds, report UI alignment leaks, and verify forms submission.",
    requirements: ["Manual Testing", "Bug Reporting", "Jira", "Excel logs", "Browser devtools"],
    benefits: ["Subsidized lunches", "Gym access", "Annual trips"],
    postedAt: "5 days ago",
    applicantsCount: 16,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-25",
    title: "Telehealth Coordinator",
    companyName: "Shifa International",
    industry: "Healthcare Systems",
    category: "Healthcare",
    logo: "SH",
    location: "Islamabad",
    salaryRange: "PKR 50k - 75k",
    jobType: "Part Time",
    experienceRequired: "1-3 Yrs",
    description: "Manage scheduling queues for online physician video consults and audit medical prescription dispatches.",
    requirements: ["Administrative tools", "Medical basic terms", "Excel logs", "Customer success"],
    benefits: ["Hospital discounts", "Leaves system", "Internet allowances"],
    postedAt: "6 days ago",
    applicantsCount: 8,
    isFeatured: false,
    isNew: false,
  },

  // === CONTRACT JOBS (10 Jobs) ===
  {
    id: "job-26",
    title: "Cloud Architect",
    companyName: "Techlogix",
    industry: "Cloud & Software",
    category: "IT & Software",
    logo: "TL",
    location: "Lahore, Punjab",
    salaryRange: "PKR 350k - 500k",
    jobType: "Contract",
    experienceRequired: "5+ Yrs",
    description: "Architect secure multi-tenant AWS cloud deployment systems, write configuration scripts, and inspect network latency.",
    requirements: ["AWS Cloud", "Terraform", "Kubernetes", "IAM Security", "System Architecture"],
    benefits: ["Premium payouts", "On-site support", "Car parking pass"],
    postedAt: "2 days ago",
    applicantsCount: 4,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-27",
    title: "Cybersecurity Auditor",
    companyName: "Systems Limited",
    industry: "IT Audit",
    category: "IT & Software",
    logo: "SL",
    location: "Islamabad",
    salaryRange: "PKR 280k - 400k",
    jobType: "Contract",
    experienceRequired: "5+ Yrs",
    description: "Conduct network penetration test audits, verify firewalls keys, and draft security threat reports.",
    requirements: ["Penetration Testing", "IPS/IDS firewalls", "OAuth logs", "Linux Server security"],
    benefits: ["Remote work support", "Project bonuses", "Learning grants"],
    postedAt: "3 days ago",
    applicantsCount: 6,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-28",
    title: "Flutter Developer",
    companyName: "Devsinc",
    industry: "Mobile Engineering",
    category: "IT & Software",
    logo: "DS",
    location: "Remote",
    salaryRange: "PKR 150k - 220k",
    jobType: "Contract",
    experienceRequired: "2-4 Yrs",
    description: "Build clean, reusable Flutter cross-platform mobile apps for corporate clients.",
    requirements: ["Flutter", "Dart", "Firebase", "State Management", "Rest APIs"],
    benefits: ["Flexible schedules", "Project milestones payouts", "Equipment grants"],
    postedAt: "4 days ago",
    applicantsCount: 19,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-29",
    title: "Technical Writer",
    companyName: "Contour Software",
    industry: "IT Services",
    category: "IT & Software",
    logo: "CS",
    location: "Karachi, Sindh",
    salaryRange: "PKR 90k - 130k",
    jobType: "Contract",
    experienceRequired: "1-3 Yrs",
    description: "Formulate code developer guidelines, draft API integration specs, and edit static page support wikis.",
    requirements: ["Technical Writing", "API Docs", "Swagger", "Git basics", "Markdown"],
    benefits: ["Learning allowances", "Flexible routines", "Paid leave pool"],
    postedAt: "5 days ago",
    applicantsCount: 11,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-30",
    title: "Data Pipeline Engineer",
    companyName: "Afiniti",
    industry: "AI & Systems",
    category: "AI & Data",
    logo: "AF",
    location: "Lahore, Punjab",
    salaryRange: "PKR 200k - 300k",
    jobType: "Contract",
    experienceRequired: "3-5 Yrs",
    description: "Build clean ETL data pipelines using python scripts, optimize SQL indexing, and connect database pools.",
    requirements: ["Python ETL", "Apache Spark", "PostgreSQL", "SQL optimization", "Docker"],
    benefits: ["Office lunches", "Project completion bonus", "Health cover"],
    postedAt: "6 days ago",
    applicantsCount: 9,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-31",
    title: "B2B Sales Agent",
    companyName: "Foodpanda",
    industry: "Food Logistics",
    category: "Sales",
    logo: "FP",
    location: "Lahore, Punjab",
    salaryRange: "PKR 80k - 120k",
    jobType: "Contract",
    experienceRequired: "1-3 Yrs",
    description: "Secure corporate partner meal plans, pitch delivery options to companies, and draft commercial agreements.",
    requirements: ["B2B sales", "Pitching deals", "Excel sheets", "Communication"],
    benefits: ["High sales commissions", "Travel fuel payouts", "Company device"],
    postedAt: "1 week ago",
    applicantsCount: 22,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "job-32",
    title: "Medical Advisor",
    companyName: "Shaukat Khanum Hospital",
    industry: "Healthcare Sector",
    category: "Healthcare",
    logo: "SK",
    location: "Peshawar, KPK",
    salaryRange: "PKR 160k - 240k",
    jobType: "Contract",
    experienceRequired: "3-5 Yrs",
    description: "Provide medical case consulting logs, verify research articles content, and audit oncology diagnostics protocols.",
    requirements: ["MBBS / Fellowship", "Oncology auditing", "Research review", "Scientific writing"],
    benefits: ["Hospital residence", "Medical coverage", "Conference passes"],
    postedAt: "2 days ago",
    applicantsCount: 3,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-33",
    title: "Corporate English Trainer",
    companyName: "Taj Institute",
    industry: "Vocational Coaching",
    category: "Education",
    logo: "TI",
    location: "Multan, Punjab",
    salaryRange: "PKR 75k - 110k",
    jobType: "Contract",
    experienceRequired: "2-4 Yrs",
    description: "Deliver professional communication training blocks to corporate employees and grade speaking exercises.",
    requirements: ["English coaching", "Instructional design", "Public speaking", "Mentoring"],
    benefits: ["Student success bonuses", "Flexible timings", "Material support"],
    postedAt: "4 days ago",
    applicantsCount: 7,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-34",
    title: "Substation Inspector",
    companyName: "K-Electric",
    industry: "Utility Power",
    category: "Engineering",
    logo: "KE",
    location: "Karachi, Sindh",
    salaryRange: "PKR 110k - 165k",
    jobType: "Contract",
    experienceRequired: "3-5 Yrs",
    description: "Inspect electrical substation grids parameters, report safety violations, and coordinate grid repairs.",
    requirements: ["Electrical basic parameters", "Grid audits", "Safety checklist", "Field work logs"],
    benefits: ["Risk allowances", "Company commute", "Daily allowances"],
    postedAt: "5 days ago",
    applicantsCount: 15,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-35",
    title: "SQL Database Consultant",
    companyName: "Punjab IT Board (PITB)",
    industry: "Government Sector",
    category: "Government",
    logo: "PI",
    location: "Lahore, Punjab",
    salaryRange: "PKR 180k - 250k",
    jobType: "Contract",
    experienceRequired: "5+ Yrs",
    description: "Consult on optimizing database servers setups, audit state database secure firewalls, and fix sql deadlocks.",
    requirements: ["MS SQL Server", "Query optimization", "Database setups", "Cluster architectures"],
    benefits: ["Pensions options", "Commute support", "Medical allowances"],
    postedAt: "6 days ago",
    applicantsCount: 12,
    isFeatured: false,
    isNew: false,
  },

  // === INTERNSHIPS (15 Jobs) ===
  {
    id: "job-36",
    title: "Software Engineering Intern",
    companyName: "Arbisoft",
    industry: "Software Engineering",
    category: "IT & Software",
    logo: "AS",
    location: "Lahore, Punjab",
    salaryRange: "PKR 25k - 35k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Work with backend developers on shipping Node.js features, write unit test scripts, and log bugs.",
    requirements: ["JavaScript basic", "Node.js basic", "Git & GitHub", "Problem solving"],
    benefits: ["Free lunch", "High conversion probability", "Technical mentoring"],
    postedAt: "1 day ago",
    applicantsCount: 45,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-37",
    title: "AI / ML Research Intern",
    companyName: "Afiniti",
    industry: "AI Services",
    category: "AI & Data",
    logo: "AF",
    location: "Islamabad",
    salaryRange: "PKR 30k - 40k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Organize raw dataset files, run training epochs for model tests, and plot convergence charts.",
    requirements: ["Python scripts", "Jupyter Notebooks", "Linear algebra basics", "Data modeling"],
    benefits: ["Device support", "Mentoring", "Corporate conversion pass"],
    postedAt: "2 days ago",
    applicantsCount: 31,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-38",
    title: "UI / UX Design Intern",
    companyName: "VentureDive",
    industry: "IT Services",
    category: "Graphic Design",
    logo: "VD",
    location: "Karachi, Sindh",
    salaryRange: "PKR 20k - 30k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Design UI layouts, create mockups, organize components, and test typography sets in Figma.",
    requirements: ["Figma layouts", "Wireframing basic", "Visual eye", "Design systems basic"],
    benefits: ["Office gym pass", "Training, courses", "Flexible shifts"],
    postedAt: "3 days ago",
    applicantsCount: 50,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-39",
    title: "Frontend React Intern",
    companyName: "Devsinc",
    industry: "IT Development",
    category: "IT & Software",
    logo: "DS",
    location: "Remote",
    salaryRange: "PKR 25k - 35k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Build landing pages elements, link forms fields to APIs, and inspect css layout leaks.",
    requirements: ["HTML & CSS", "JavaScript basic", "React hooks basic", "Responsive web design"],
    benefits: ["Remote work flexibility", "Bonus allocations", "Internet stipends"],
    postedAt: "4 days ago",
    applicantsCount: 68,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-40",
    title: "Python Developer Intern",
    companyName: "NetSol Technologies",
    industry: "IT & Systems",
    category: "IT & Software",
    logo: "NS",
    location: "Lahore, Punjab",
    salaryRange: "PKR 30k - 40k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Assist coding squads in writing unit test scripts, verify database tables schema, and clear python issues.",
    requirements: ["Python programming", "SQL basics", "Git commands", "Data structs"],
    benefits: ["Corporate meals", "Transport facility", "Paid certification supports"],
    postedAt: "5 days ago",
    applicantsCount: 42,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-41",
    title: "HR Recruitment Intern",
    companyName: "Systems Limited",
    industry: "IT Sourcing",
    category: "HR & Recruitment",
    logo: "SL",
    location: "Karachi, Sindh",
    salaryRange: "PKR 20k - 30k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Scan candidate resumes, schedule interviews calls, and log recruiting feedback in spreadsheet dashboards.",
    requirements: ["Excel spreadsheets", "Communications", "Sifting candidate logs", "Word tools"],
    benefits: ["Annual certificate", "Transport pool support", "Cafeteria discount card"],
    postedAt: "6 days ago",
    applicantsCount: 27,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-42",
    title: "Digital Marketing Intern",
    companyName: "Daraz",
    industry: "E-commerce Sector",
    category: "Marketing",
    logo: "DZ",
    location: "Remote",
    salaryRange: "PKR 22k - 32k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Draft text blurbs for social ads, collect keyword metrics logs, and verify display campaign formats.",
    requirements: ["Ad copywriting", "SEO basic metrics", "Social platforms logs", "Canva basics"],
    benefits: ["Employee discount coupons", "Mobile stipends", "Conversion tracking paths"],
    postedAt: "1 week ago",
    applicantsCount: 39,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "job-43",
    title: "E-commerce Operations Intern",
    companyName: "Foodpanda",
    industry: "Food Delivery Tech",
    category: "Sales",
    logo: "FP",
    location: "Lahore, Punjab",
    salaryRange: "PKR 25k - 35k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Verify retail menu prices catalog setups, update merchant files info, and monitor delivery speed logs.",
    requirements: ["Data entry basic", "Communication", "Troubleshooting basic", "Google sheets"],
    benefits: ["Subsidized meals", "Work gear allowances", "Paid leave options"],
    postedAt: "2 days ago",
    applicantsCount: 18,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-44",
    title: "Finance & Auditing Intern",
    companyName: "KPMG Pakistan",
    industry: "Financial Audit",
    category: "Finance",
    logo: "KP",
    location: "Karachi, Sindh",
    salaryRange: "PKR 25k - 35k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Cross reference bank transactions lists, verify tax registers invoices, and organize spreadsheet logs.",
    requirements: ["Excel filters", "Financial accounting basic", "Attention to detail", "Calculations"],
    benefits: ["Training certificates", "Transport support pool", "Overtime dinners"],
    postedAt: "4 days ago",
    applicantsCount: 26,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-45",
    title: "Customer Success Intern",
    companyName: "Zong 4G (CMPak)",
    industry: "Telecom Network",
    category: "Customer Support",
    logo: "ZO",
    location: "Rawalpindi, Punjab",
    salaryRange: "PKR 18k - 25k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Answer online chat query tickets from users, and guide them through corporate subscription activations.",
    requirements: ["Typing speed", "Polite dialogue", "Troubleshooting basics", "CRM systems basics"],
    benefits: ["Subsidized dinners", "Medical insurance basic", "Leaves allocation"],
    postedAt: "5 days ago",
    applicantsCount: 33,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "job-46",
    title: "Node.js Backend Intern",
    companyName: "10Pearls",
    industry: "IT Development",
    category: "IT & Software",
    logo: "10P",
    location: "Karachi, Sindh",
    salaryRange: "PKR 25k - 35k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Draft Node.js api endpoints routes, log PostgreSQL schema tables data, and resolve simple code bugs.",
    requirements: ["JavaScript basics", "SQL querying basics", "Express routes", "Debugging logs"],
    benefits: ["Paid certification pool", "Gym facility access", "Flexible schedule options"],
    postedAt: "6 days ago",
    applicantsCount: 48,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-47",
    title: "Data Analytics Intern",
    companyName: "Systems Limited",
    industry: "IT Sprints",
    category: "AI & Data",
    logo: "SL",
    location: "Lahore, Punjab",
    salaryRange: "PKR 30k - 40k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Assist backend database leads in sifting data reports, auditing log metrics, and mapping values lists.",
    requirements: ["Python data tools", "Excel dashboard filters", "SQL query basic", "Communication"],
    benefits: ["Gratuity points", "Corporate conversion pass", "Meal vouchers"],
    postedAt: "1 week ago",
    applicantsCount: 52,
    isFeatured: true,
    isNew: false,
  },
  {
    id: "job-48",
    title: "Medical Records Intern",
    companyName: "Shifa International",
    industry: "Healthcare Services",
    category: "Healthcare",
    logo: "SH",
    location: "Islamabad",
    salaryRange: "PKR 20k - 28k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Organize patient files data inputs inside medical logs system, check spelling compliance, and catalog reports.",
    requirements: ["Database entry", "Medical terminology basic", "Word tools", "Detail checking"],
    benefits: ["Hospital outpatient discounts", "Leaves support", "Internet stipends"],
    postedAt: "2 days ago",
    applicantsCount: 15,
    isFeatured: false,
    isNew: true,
  },
  {
    id: "job-49",
    title: "Civil Construction Intern",
    companyName: "Habib Construction Services",
    industry: "Infrastructure Engineering",
    category: "Engineering",
    logo: "HC",
    location: "Multan, Punjab",
    salaryRange: "PKR 22k - 30k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Help site engineer logs site supplies volumes, inspect daily concrete curing, and verify safety checklist.",
    requirements: ["Civil engineering basic", "AutoCAD reader", "Excel checklists", "Detail mapping"],
    benefits: ["Risk gear allocation", "Site travel stipends", "Leaves pool"],
    postedAt: "4 days ago",
    applicantsCount: 22,
    isFeatured: false,
    isNew: false,
  },
  {
    id: "job-50",
    title: "Web Content Intern",
    companyName: "Punjab IT Board (PITB)",
    industry: "Government Sector",
    category: "Government",
    logo: "PI",
    location: "Lahore, Punjab",
    salaryRange: "PKR 25k - 35k",
    jobType: "Internship",
    experienceRequired: "Fresh / Intern",
    description: "Update static page content blocks inside government web directories, proofread descriptions, and log suggestions.",
    requirements: ["Word editing", "Google search basics", "Excel sheets logging", "HTML basic tagging"],
    benefits: ["Government training badges", "Commute allowances", "Cafeteria passes"],
    postedAt: "5 days ago",
    applicantsCount: 39,
    isFeatured: true,
    isNew: true,
  }
];

const mockApplications: JobApplication[] = [
  {
    id: "app-1",
    jobId: "job-1",
    jobTitle: "Senior Frontend Developer",
    companyName: "Systems Limited",
    candidateId: "cand-1",
    candidateName: "Ahmad Raza",
    candidateTitle: "Frontend Developer",
    status: "Interview Scheduled",
    appliedDate: "10 May 2026",
    cvUrl: "/resumes/ahmad_raza.pdf",
    coverLetter: "I am excited to apply for the Senior Frontend Developer position at Systems Limited. With my extensive background in React.js and TypeScript, I am confident I can contribute from day one.",
    matchScore: 95,
  },
  {
    id: "app-2",
    jobId: "job-5",
    jobTitle: "UX Researcher",
    companyName: "Systems Limited",
    candidateId: "cand-2",
    candidateName: "Fatima Shah",
    candidateTitle: "UX Researcher",
    status: "Under Review",
    appliedDate: "12 May 2026",
    cvUrl: "/resumes/fatima_shah.pdf",
    coverLetter: "I specialize in human-computer interaction, usability testing, and qualitative user research for digital products.",
    matchScore: 80,
  },
  {
    id: "app-3",
    jobId: "job-3",
    jobTitle: "Product Designer",
    companyName: "10Pearls",
    candidateId: "cand-3",
    candidateName: "Bilal Hassan",
    candidateTitle: "Product Designer",
    status: "Shortlisted",
    appliedDate: "8 May 2026",
    cvUrl: "/resumes/bilal_hassan.pdf",
    coverLetter: "Design and design systems go hand in hand. I bring over 4 years of experience architecting user flows and Figma component libraries.",
    matchScore: 91,
  },
];

const initialFilters: FilterSettings = {
  keyword: "",
  location: "",
  minSalary: "Min",
  maxSalary: "Max",
  experience: "Any experience",
  jobType: "All types",
  isRemote: false,
};

export const useJobStore = create<JobState>()(
  persist(
    (set, get) => ({
      jobs: defaultJobs,
      applications: mockApplications,
      savedJobIds: ["job-1", "job-4"],
      filters: initialFilters,

      setFilters: (newFilters) => {
        set((state) => ({
          filters: { ...state.filters, ...newFilters },
        }));
      },

      resetFilters: () => {
        set({ filters: initialFilters });
      },

      postJob: (jobData) => {
        const newJob: Job = {
          ...jobData,
          id: `job-${Math.random().toString(36).substring(7)}`,
          postedAt: "Just now",
          applicantsCount: 0,
          isNew: true,
          matchScore: 100, // Default for testing
        };

        set((state) => ({
          jobs: [newJob, ...state.jobs],
        }));
      },

      editJob: (id, updatedJob) => {
        set((state) => ({
          jobs: state.jobs.map((j) => (j.id === id ? { ...j, ...updatedJob } : j)),
        }));
      },

      deleteJob: (id) => {
        set((state) => ({
          jobs: state.jobs.filter((j) => j.id !== id),
          applications: state.applications.filter((a) => a.jobId !== id),
        }));
      },

      applyJob: (jobId, candidateId, candidateName, candidateTitle, coverLetter, matchScore) => {
        const job = get().jobs.find((j) => j.id === jobId);
        if (!job) return;

        // Check if already applied
        const alreadyApplied = get().applications.some(
          (a) => a.jobId === jobId && a.candidateId === candidateId
        );
        if (alreadyApplied) return;

        const score = matchScore || job.matchScore || 75;

        const newApplication: JobApplication = {
          id: `app-${Math.random().toString(36).substring(7)}`,
          jobId,
          jobTitle: job.title,
          companyName: job.companyName,
          candidateId,
          candidateName,
          candidateTitle,
          status: "Under Review",
          appliedDate: new Date().toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          }),
          cvUrl: "/resumes/resume.pdf",
          coverLetter,
          matchScore: score,
        };

        // Increment applicants count
        set((state) => ({
          applications: [newApplication, ...state.applications],
          jobs: state.jobs.map((j) =>
            j.id === jobId ? { ...j, applicantsCount: j.applicantsCount + 1 } : j
          ),
        }));
      },

      updateApplicationStatus: (applicationId, status) => {
        set((state) => ({
          applications: state.applications.map((a) =>
            a.id === applicationId ? { ...a, status } : a
          ),
        }));
      },

      toggleSaveJob: (jobId) => {
        set((state) => {
          const isSaved = state.savedJobIds.includes(jobId);
          return {
            savedJobIds: isSaved
              ? state.savedJobIds.filter((id) => id !== jobId)
              : [...state.savedJobIds, jobId],
          };
        });
      },

      calculateMatchScore: (candidateSkills, jobRequirements) => {
        if (!jobRequirements || jobRequirements.length === 0) return 100;
        
        let matchCount = 0;
        let totalScore = 0;

        jobRequirements.forEach((req) => {
          const matchedSkill = candidateSkills.find(
            (s) => s.name.toLowerCase().includes(req.toLowerCase()) || 
                   req.toLowerCase().includes(s.name.toLowerCase())
          );
          if (matchedSkill) {
            matchCount++;
            totalScore += matchedSkill.rating;
          }
        });

        if (matchCount === 0) return 30; // Base background match
        
        // Calculate weighted percentage
        const matchPercentage = (matchCount / jobRequirements.length) * 100;
        const averageRating = totalScore / matchCount;
        
        // Return average of match scale and specific ratings
        return Math.round((matchPercentage + averageRating) / 2);
      },
    }),
    {
      name: "titan-job-storage-v2",
    }
  )
);
